### ISSUE TITLE
[REQUEST] Improve system prompt handling for models that do not include system role

### ISSUE THREAD

**Issue by arbi-dev** [theroyallab/tabbyAPI#148]
Some models (e.g. Gemma 2) that can be loaded with TabbyAPI/exllama2 do not accept system prompts and throw an exception if a system prompt is included in the api call. E.g. Gemma2 Tokenizer.json) "chat_template": "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}

While in an ideal world there would be no system message included in such API calls in the first place, some apps that are tuned to work with OpenAI-compatible backends always include a system prompt (eg. AnythingLLM).  

Accordingly, it would be nice if the backend API could gracefully mediate the issue -- e.g. by issuing a warning but discarding the system message and processing the other messages as normal for models that don't support it.  Of course there could be even better ways to handle -- not sure.

**Comment by bdashore3** [comment]
The error is because of Google's template, not TabbyAPI. To fix this on your end, you can create a custom Jinja2 template, place it in the `templates` folder and set the `prompt_template` var to the filename of that template.

Documentation: [https://github.com/theroyallab/tabbyAPI/wiki/4.-API#4c-chat-completions](https://github.com/theroyallab/tabbyAPI/wiki/4.-API#4c-chat-completions)

**Comment by arbi-dev** [comment]
Thank you for the reply, very helpful! If this is a unique issue to Gemma2, the custom template path makes sense, unless they issue a fix. But if this kind of issue affects other models, having to create a custom template every time is probably not the ideal solution.

**Comment by TyraVex** [comment]
While I understand this issue might come from the model authors' decisions, I believe it would be beneficial for TabbyAPI to offer an option in the config.yml to skip the error and ignore the system prompt. This way, Tabby doesn't have to make decisions by itself, while solving this issue in a generalized way for all similar models.

**Comment by DocShotgun** [comment]
Well, you can't simply "skip" an error - something else has to be done to handle the exception instead of erroring out. Since the jinja2 template could raise an exeption for any arbitrary reason that the author could script in, there isn't really a one-size-fits-all way of handling it.

For example, the new mistral 12b model's template is explicitly written to error out if:
1) A system role message exists but is not the first message
2) Messages do not alternate user/assistant/user/assistant after the initial optional system role message
3) Any different role is provided for a message

If you wanted to bypass this, you'd need to rewrite the jinja2 template to format the prompt instead of erroring out. Although you'd need to make some judgement calls on what you want the template to do in those situations instead, since this template is not designed to function outside of those scenarios. Mistral's template only includes wrapping sequences for the user role, and everything outside of them is assumed to be assistant role. No actual sequences exist for the system role - the template just tacks it onto the beginning of the first user message. This is unlike ChatML or Llama 3 instruct, which don't really care if those conditions are violated because every message from every role has its own wrapping sequences.

**Comment by bdashore3** [comment]
Agreed. Tabby tries to make things "just work" within reason, but chat templates are a variable part of models that don't have specific exceptions by design. If something errors, it means the author didn't intend for that usecase and you should make your own that fits the usecase.

There is a [prompt templates](https://github.com/theroyallab/llm-prompt-templates) hosted repository which hosts unrestricted templates and PRs there are welcome, but there won't be any changes to tabby at this time due to the unpredictability of templates as a whole.

**Comment by arbi-dev** [comment]
I think the real issue here is not the model provider, it's up to them what
parameters to support in their template.  The issue is with the API calls
which are OAI compatible but not compatible with certain non-OAI models
supported by Tabby.  Some middleware like API gateways expressly allow you
to drop unsupported model params before making the API call:
https://litellm.vercel.app/docs/completion/drop_params.     However that is
not always the case.
Accordingly, it's a real issue that will cause failures for certain users.
Rather than forcing every user to figure out what the problem is and
manually edit templates to create a solution, it would be really helpful if
Tabby could at least have a note in the docs with an example of how to fix
the issue, so everyone does not have to figure it out for themselves.  I
appreciate it's not Tabby's job to fix all API schema incompatibilities,
but I think it would be better not to leave users on their own.

**Comment by DocShotgun** [comment]
The issue is there isn’t a blanket way to anticipate what exactly isn’t compatible with what model (or template, rather), since the jinja2 template is essentially a third-party script to format the prompt. Llama.cpp server’s solution to this is to just only allow a certain set of hardcoded templates, which favors ease of use over flexibility. The exception raised by the jinja2 template is already informative enough as to what the problem is.
