### ISSUE TITLE
[REQUEST] Add support for new output formatter Formatron

### ISSUE THREAD

**Issue by saturosfz** [theroyallab/tabbyAPI#212]
### Solution

Formatron has a [filter](https://github.com/Dan-wanna-M/formatron/blob/master/src/formatron/integrations/exllamav2.py) supporting exllamav2, so the integration seems to be easy.

### Explanation

Said to be faster than LM Format Enforcer and Outlines (see [benchmark](https://github.com/Dan-wanna-M/formatron/blob/master/benchmarks/readme.md)).

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by bdashore3** [comment]
This is planned for newer versions, but unfortunately this isn't as easy as stated.

Currently blocking on better JSON schema support on formatron's side: https://github.com/Dan-wanna-M/formatron/issues/12

I'm open to ideas to make a larger subset of JSON schema features work without any extra dependencies (besides formatron) and without a ton of overengineered code for reinventing the wheel.

**Comment by Dan-wanna-M** [comment]
Note that since `v0.4.6` formatron has supported a wider subset of JSON schema.

> I'm open to ideas to make a larger subset of JSON schema features work without any extra dependencies (besides formatron) and without a ton of overengineered code for reinventing the wheel.'

After spending tons of hours reading json schema's reference and specification and coding to support such features, I suspect there is *not* a way to achieve this without a ton of overengineered code——json schema itself really looks like a lot of overengineered stuffs glued together into a giant toolkit so that different people can use *different* subsets of it for convenience. Put it the other way, it is originally exclusively designed to facilitate using serializable common validation logic during runtime, which leads to tons of behaviours that can be easily checked during runtime with a Turing-complete language but embrassing or even impossible to be done statically, which includes with a context free grammar. That's why there is no existing code that tries to do so(I believe Outlines also has its own transformation, just into regular expressions rather than context free grammars)

**Comment by bdashore3** [comment]
Hey @Dan-wanna-M,

I completely understand where you're coming from. JSON schema (like most things in AI) are over engineered. I'm mainly asking to have support for JSON schemas as a functional equivalent to LMFE or what users use for llama.cpp.

However, I'm not 100% sure what LMFE supports or what users specifically need from JSON schema.

I'm also happy to message on discord, join the server in the README and I'll be happy to talk.

**Comment by saturosfz** [comment]
TabbyAPI with formatron basically works under exllamav2 dev branch, and is much faster than lmfe, in my ragged implementation. Looking forward to more polished version.
