### ISSUE TITLE
[BUG] Much slower than vllm/lmdeploy and GPU utilization is low

### ISSUE THREAD

**Issue by fzyzcjy** [theroyallab/tabbyAPI#259]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

Hi thanks for the library! It seems that tabbyapi is much slower than vllm/lmdeploy, and at the same time, the GPU utilization is much lower.

The speed of lmdeploy is ~2 minute, while tabbyapi is ~7 minute.

Example GPU utilization (left: lmdeploy, right: tabbyapi)

![image](https://github.com/user-attachments/assets/8d367fb0-7ae3-47c7-9ed7-5e8ee0bafd94)

### Reproduction steps

I am trying https://huggingface.co/DrNicefellow/Qwen2.5-Math-7B-Instruct-4.0bpw-exl2 with 1000 math questions.

### Expected behavior

(see above)

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
Can you elaborate on the hardware setup, how you've configured Tabby (cache size etc.) and how you're running this test?

**Comment by fzyzcjy** [comment]
Hi thanks for the reply!

* RTX 4090D
* cache_size=344064
* Use tabbyapi to start an openai compatible server, and then submit 1000 requests to it

**Comment by fzyzcjy** [comment]
Btw, I wonder whether tabbyapi is roughly the same speed as vllm/lmdeploy, or it is known to be slower? If the latter then I may not experiment more and just wait a bit of time and retry when tabbyapi is grown to be faster.

**Comment by Originalimoc** [comment]
cache_size 344k? Are you sure does Qwen2.5-Math-7B-Instruct even support 32k+ like common 2.5-7B? The util graph seems like VRAM full and swapping to system RAM.

**Comment by fzyzcjy** [comment]
I am hoping to have large batch size. For example, in vllm or lmdeploy, I can use batch size 512, and each request is about 1000 token, and that speed up a lot.

**Comment by DocShotgun** [comment]
I wouldn't expect tabby/exl2 to match vLLM's performance with batching as exl2's original target usecase, and what it's optimized for, is batch size 1 inference on modern consumer hardware (not that it hasn't expanded its feature base now!), while vLLM has always been built for serving at a larger scale. From my understanding, quantized models also suffer in speed compared to fp16 models at such larger batch sizes when you become compute bound.

Would you mind sharing the complete model load settings? Are you using Q4 cache to fit such a large number of cache tokens? All of the Q-cache options in exl2 actually reduce speed due to the need for dequantization, as the kernels do not infer natively with Q4/6/8 cache.

**Comment by fzyzcjy** [comment]
Thanks! Yes I am trying q8 and q4 cache for larger batch sizes.
