### ISSUE TITLE
[REQUEST] Auto Max Tokens

### ISSUE THREAD

**Issue by sitbk** [theroyallab/tabbyAPI#86]
**Is your feature request related to a problem? Please describe.**
I'm relatively new to the realm of LLMs. Coming from text-generation-webui, it seems to automagically calculate the max_tokens based on the prompt length and max sequence length. TabbyAPI does not seem to do this by default, unless I'm missing a setting somewhere. I know it technically can be calculated client-side and sent as a parameter. 

**Describe the solution you'd like**
Automatic calculation based upon the max sequence length in the configuration file and length of the received prompt. 

**Describe alternatives you've considered**
I've manually patched this together in `backends/exllamav2/model.py` by re-calculating max_tokens with `max_tokens = self.config.max_seq_len - prompt_tokens`. 

**Why should this feature be added?**
Ease of use with less flexible clients, as TabbyAPI appears to only support a static max_tokens (default: 150) on server-side.

**Additional context**
Willing to help implement this providing there isn't a legitimate reason to avoid automatic generation of max_tokens.

**Comment by bdashore3** [comment]
Added in 09a4c79

But, for some clarification, text-generation-webui doesn't behave like this by default. Please see [this snippet](https://github.com/oobabooga/text-generation-webui/blob/7cf1402bde48fd76af501d5efecb34227bf4d082/extensions/openai/completions.py#L90-L91) and the [default for max_tokens](https://github.com/oobabooga/text-generation-webui/blob/7cf1402bde48fd76af501d5efecb34227bf4d082/extensions/openai/typing.py#L60) in their OpenAI API (16, which is the default on OpenAI's website). Use the `auto_max_new_tokens` parameter in TGW to get the behavior you're expecting.

In tabby, the reasoning behind 150 was because OAI's default (16) was too small and didn't make much sense, so I welcome this change. To override the auto scaling or any other sampling parameter, please look into sampler overrides.
