### ISSUE TITLE
[REQUEST]  rope_freq_base ?

### ISSUE THREAD

**Issue by Lynch96** [theroyallab/tabbyAPI#90]
Hi there

i was wondering if there is any way to currently change rope_freq_base in the config?
Or could this be added in?
This can be done in TGWUI & can help fix looping in mixtral models 

thanks
L

**Comment by turboderp** [comment]
An indirect way would be to change the `rope_alpha` parameter since all that does is scale the rotary embedding base. The scaling is nonlinear, with the exact scale factor being:

`rope_alpha^(head_dim / (head_dim - 2))`

For most models that means:

`rope_alpha^1.01587`

In other words, if your model has a base of 10,000 and you want to inference as if it had a base of 35,000, you would set:

`rope_alpha = (35000/10000)^(1/1.01587) = 3.4321`

Since what you're doing doesn't sound especially scientific you're probably fine just setting:

`rope_alpha = (35000/10000) = 3.5`

You can also edit the model's config.json directly. The `rope_theta` parameter sets the embedding base, and if it's not present you can add it to override the default of 10,000. Are you sure this is the setting you want to change, though? The only reason it would work is if it gives the model a fuzzier recollection of its the context, which sounds like a very drastic measure compared to just choosing better sampling parameters.. ?

**Comment by bdashore3** [comment]
NOTICE: Please use the issue template when creating issues. 

I don't mind adding a rope_freq_base parameter for convenience, but I also agree with what turbo said. Rope alpha already exists which achieves the same goal. In fact, tabby can calculate an alpha value by just adjusting the max_seq_len and not explicitly setting rope_alpha. However, using rope_freq_base to prevent model looping is pretty extreme and vram heavy. It may be better to look at your sampling parameters (specifically repetition penalty and penalty range).
