### ISSUE TITLE
[REQUEST] Providing response prefixes

### ISSUE THREAD

**Issue by andysalerno** [theroyallab/tabbyAPI#96]
**Is your feature request related to a problem? Please describe.**
It's very helpful to provide the first few lines of a response for the model to complete.

I.e. "Yes, I can help with that, first I will X and then I will Y, here we go:"

That's a very simplistic made up example, but there are many scenarios where this is useful to guide the model down the right path before letting it complete the response.

**Describe the solution you'd like**
One possibility is to have a special property like "prefix" on the chat request message.

Another possibility is to have a boolean flag like "continue_last_message" where the LLM will simply continue completions for the last message, and users can make the last message be the prefix they want from the assistant.

**Describe alternatives you've considered**
Considered using grammars or json schema for this, but grammar is overkill (I don't want a EBNF grammar just for a prefix) and json schema doesn't do exactly what I want.

**Why should this feature be added?**
It's super useful to make requests where you give a prefix that sets the model on the correct path, before allowing to to continue.

**Comment by bdashore3** [comment]
Rather than a backend thing, this request is more prompt engineering and frontend related. I actually added this in [SillyTavern](https://github.com/SillyTavern/SillyTavern) under `Start reply with`. Feel free to try it out there.

Basically, in a request, set your prompt to something like this:
```
User: "Tell me a joke"
Assistant: "Do you know
```

And this will make the model complete the sentence with that prefix. Of course you should apply proper instruct formatting for that model when prompting it.

Here's another example for chat completions:
```json
"messages": [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "Hello! Tell me a joke."
    },
    {
        "role": "assistant",
        "content": "You ever hear of"
    }
],
"add_generation_prompt": false
```

It's important to set `add_generation_prompt` to `false` here since Tabby won't append an assistant response to the end of the Jinja generated prompt.

And this yields a response of:
```json
"message": {
    "role": "assistant",
    "content": " the guy who's afraid of his shadow? That's the darkness within him."
},
```

These messages can be squashed together into one assistant message. I'd advise changing the frontend/inference code to use a method like this one.

**Comment by andysalerno** [comment]
Thanks for the response!

I see what you're saying, but don't fully agree-

It's not enough to set `add_generation_prompt` to false, because most prompt formats are generally like so (psuedo-Jinja): 

```
{% for message in messages %}
    <start_tok>some message content<end_tok>
{% end loop %}
{% if add_generation_prompt %}
    <start_tok>
{% end if %}
```

Meaning, if using the `/chat/completions` endpoint, all messages will always be **terminated with the ending token** before getting passed to the LLM. Simply omitting `add_generation_prompt` will prevent the *start* of the assistant turn from getting added, but it doesn't prevent the *end* of the previous turn from getting terminated, making it impossible to provide a prefix for the assistant.

On the matter of "This should be done in the client", the reason I disagree with this is because now the client needs to know the specific templating details of the model, which may change per-model, and is generally not something a client should have to bother with when hitting a chat completions endpoint.

So it would be super convenient if the client could just inform the API - "Hey, whatever template you are using, I don't care, just please start your next response with this prefix"

**Comment by DocShotgun** [comment]
>Meaning, if using the /chat/completions endpoint, all messages will always be terminated with the ending token before getting passed to the LLM. Simply omitting add_generation_prompt will prevent the start of the assistant turn from getting added, but it doesn't prevent the end of the previous turn from getting terminated, making it impossible to provide a prefix for the assistant.

I'm not sure I understand this part. Why wouldn't you want the previous turn to be terminated? The response prefix is being applied to the new turn being generated, not the previous user turn. This would be more like applying a last user turn suffix instead if the previous response was left un-terminated.

>On the matter of "This should be done in the client", the reason I disagree with this is because now the client needs to know the specific templating details of the model, which may change per-model, and is generally not something a client should have to bother with when hitting a chat completions endpoint.

I think this is a reasonable consideration as the frontend won't necessarily know what the model's prompt format is.

**Comment by bdashore3** [comment]
Yeah, those are fair points. I added the parameter in the above commit. The main gripe I had is bloating the API request, but since this seems to be something that many people would use, I agree that this should be a parameter.

However, this (and many other things) can be achieved with the `template_vars` parameter as an alternative method using a custom template.

Example:
```jinja
{% for message in messages %}
    <start_tok>some message content<end_tok>
{% end loop %}
{% if add_generation_prompt %}
    <start_tok>{{prefix}}
{% end if %}
```

And in the request
```json
{
    "template_vars": {
        "prefix": "Hey there!"
    }
}
```

**Comment by bdashore3** [comment]
Closing this issue since it's stale and the functionality was added.
